# Generated by Django 3.2.7 on 2021-09-25 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_copies', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=240)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instrument.instrument')),
            ],
        ),
    ]
