# Generated by Django 3.2.7 on 2021-09-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
    ]
