# Generated by Django 3.2.7 on 2021-09-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='piece.category'),
            preserve_default=False,
        ),
    ]
