# Generated by Django 3.2.7 on 2021-09-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0003_piece_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='catalogue_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
