# Generated by Django 3.2.7 on 2021-09-25 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0004_piece_catalogue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
