# Generated by Django 3.2.7 on 2021-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0005_auto_20210925_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='grade',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='isbn',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
