# Generated by Django 3.2.7 on 2021-09-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0007_auto_20210925_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='group',
            new_name='instrument_group',
        ),
    ]
