# Generated by Django 3.2.7 on 2021-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0008_rename_group_instrument_instrument_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
            ],
        ),
    ]
