# Generated by Django 3.2.7 on 2021-09-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0010_piece_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='missing_parts',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='piece.location'),
            preserve_default=False,
        ),
    ]
