# Generated by Django 3.2.7 on 2021-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0012_composer'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='composers',
            field=models.ManyToManyField(to='piece.Composer'),
        ),
    ]
