# Generated by Django 3.2.7 on 2021-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0013_piece_composers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='composer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='instrumentgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['instrument', 'category', 'catalogue_number', 'title']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='piece',
            name='accompaniment',
            field=models.ManyToManyField(related_name='instrument_accompaniment', to='piece.Instrument'),
        ),
    ]
