# Generated by Django 3.2.7 on 2021-09-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0015_auto_20210925_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='notes',
            field=models.TextField(default='Blank'),
            preserve_default=False,
        ),
    ]
