# Generated by Django 3.2.7 on 2021-09-25 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0016_piece_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='date_last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
