# Generated by Django 3.2.7 on 2021-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0017_piece_date_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date_last_checked',
            field=models.DateField(),
        ),
    ]
