# Generated by Django 3.2.7 on 2021-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0018_alter_piece_date_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date_last_checked',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='grade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='piece',
            name='isbn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='piece',
            name='missing_parts',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='piece',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
