# Generated by Django 3.2.7 on 2021-09-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0019_auto_20210925_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='accompaniment',
            field=models.ManyToManyField(blank=True, related_name='instrument_accompaniment', to='piece.Instrument'),
        ),
    ]
