# Generated by Django 4.0.3 on 2022-04-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0020_alter_piece_accompaniment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['code', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['instrument_group', 'name']},
        ),
    ]
