# Generated by Django 4.0.3 on 2022-04-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0021_alter_category_options_alter_instrument_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arranger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EnsemblePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sacred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='piece',
            name='grade',
        ),
        migrations.AddField(
            model_name='piece',
            name='arrangement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='medley',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='piece',
            name='movements',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='piece',
            name='number_of_originals',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='piece',
            name='performance_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='sacred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='piece',
            name='soloists',
            field=models.ManyToManyField(blank=True, null=True, related_name='instrument_soloists', to='piece.instrument'),
        ),
        migrations.AddField(
            model_name='piece',
            name='song_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='year_last_performed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='year_purchased',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='accompaniment',
            field=models.ManyToManyField(blank=True, null=True, related_name='instrument_accompaniment', to='piece.instrument'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composers',
            field=models.ManyToManyField(blank=True, null=True, to='piece.composer'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='missing_parts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='arrangers',
            field=models.ManyToManyField(blank=True, null=True, to='piece.arranger'),
        ),
        migrations.AddField(
            model_name='piece',
            name='ensemble_parts',
            field=models.ManyToManyField(blank=True, null=True, to='piece.ensemblepart'),
        ),
        migrations.AddField(
            model_name='piece',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='piece.genre'),
        ),
        migrations.AddField(
            model_name='piece',
            name='grades',
            field=models.ManyToManyField(blank=True, null=True, to='piece.grade'),
        ),
        migrations.AddField(
            model_name='piece',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='piece.status'),
        ),
    ]
