# Generated by Django 4.0.3 on 2022-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0022_arranger_ensemblepart_genre_grade_sacred_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='accompaniment',
            field=models.ManyToManyField(blank=True, related_name='instrument_accompaniment', to='piece.instrument'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='arrangers',
            field=models.ManyToManyField(blank=True, to='piece.arranger'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composers',
            field=models.ManyToManyField(blank=True, to='piece.composer'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='ensemble_parts',
            field=models.ManyToManyField(blank=True, to='piece.ensemblepart'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='grades',
            field=models.ManyToManyField(blank=True, to='piece.grade'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='soloists',
            field=models.ManyToManyField(blank=True, related_name='instrument_soloists', to='piece.instrument'),
        ),
    ]
