# Generated by Django 4.0.3 on 2022-04-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0024_alter_piece_category_alter_piece_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='categories',
            field=models.ManyToManyField(to='piece.category'),
        ),
        migrations.AddField(
            model_name='piece',
            name='instruments',
            field=models.ManyToManyField(to='piece.instrument'),
        ),
    ]
