# Generated by Django 4.0.3 on 2022-04-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0026_remove_instrumentgroup_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='accompaniment_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
