# Generated by Django 4.0.3 on 2022-04-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0027_piece_accompaniment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='related_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
