# Generated by Django 4.0.3 on 2022-04-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0028_piece_related_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_category', to='piece.category'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_instrument', to='piece.instrument'),
        ),
    ]
