# Generated by Django 4.0.3 on 2022-04-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0029_alter_piece_category_alter_piece_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='medley',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='movements',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='sacred',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
