# Generated by Django 4.0.3 on 2022-05-01 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0030_alter_piece_medley_alter_piece_movements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='piece',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_location', to='piece.location'),
        ),
    ]
