# Generated by Django 4.0.3 on 2022-05-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0031_alter_status_options_alter_piece_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='locations',
            field=models.ManyToManyField(to='piece.location'),
        ),
    ]
