# Generated by Django 4.1.5 on 2023-01-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0032_piece_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ShelfLocation',
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shelflocation',
            options={'ordering': ['code', 'name'], 'verbose_name_plural': 'Shelf Locations'},
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='categories',
            new_name='shelf_locations',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='category',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='location',
        ),
    ]
