# Generated by Django 4.1.5 on 2023-01-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0035_remove_piece_genre_piece_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='genre',
            new_name='genres',
        ),
    ]
