# Generated by Django 4.1.5 on 2023-02-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0036_rename_genre_piece_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='instruments_secondary',
            field=models.ManyToManyField(blank=True, related_name='instruments_secondary', to='piece.instrument'),
        ),
    ]
